/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_intel_analytics_bigdl_mkl_hardware_platform_linux_LinuxNativeUtils */

#ifndef _Included_com_intel_analytics_bigdl_mkl_hardware_platform_linux_LinuxNativeUtils
#define _Included_com_intel_analytics_bigdl_mkl_hardware_platform_linux_LinuxNativeUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_intel_analytics_bigdl_mkl_hardware_platform_linux_LinuxNativeUtils
 * Method:    getTaskId0
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_intel_analytics_bigdl_mkl_hardware_platform_linux_LinuxNativeUtils_getTaskId0
  (JNIEnv *, jclass);

/*
 * Class:     com_intel_analytics_bigdl_mkl_hardware_platform_linux_LinuxNativeUtils
 * Method:    getPid0
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_intel_analytics_bigdl_mkl_hardware_platform_linux_LinuxNativeUtils_getPid0
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
