/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_intel_analytics_bigdl_mkl_hardware_platform_linux_LinuxAffinity */

#ifndef _Included_com_intel_analytics_bigdl_mkl_hardware_platform_linux_LinuxAffinity
#define _Included_com_intel_analytics_bigdl_mkl_hardware_platform_linux_LinuxAffinity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_intel_analytics_bigdl_mkl_hardware_platform_linux_LinuxAffinity
 * Method:    setAffinity0
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_com_intel_analytics_bigdl_mkl_hardware_platform_linux_LinuxAffinity_setAffinity0
  (JNIEnv *, jclass, jintArray);

/*
 * Class:     com_intel_analytics_bigdl_mkl_hardware_platform_linux_LinuxAffinity
 * Method:    getAffinity0
 * Signature: ([II)I
 */
JNIEXPORT jint JNICALL Java_com_intel_analytics_bigdl_mkl_hardware_platform_linux_LinuxAffinity_getAffinity0
  (JNIEnv *, jclass, jintArray, jint);

#ifdef __cplusplus
}
#endif
#endif
