#ifndef ARCH_CONFIG_H
#define ARCH_CONFIG_H

typedef enum CPU_FEATURE {SSE4_2=0, AVX2_FMA=1, AVX_512=2} CPU_FEATURE;

#if defined(AVX512)
#define GEMM_SHUFFLE_KERNEL_M 4
#define GEMM_SHUFFLE_KERNEL_N 4
#define GEMM_SHUFFLE_KERNEL_K 64
#define CONV_SHUFFLE_KERNEL_M GEMM_SHUFFLE_KERNEL_M
#define CONV_SHUFFLE_KERNEL_N GEMM_SHUFFLE_KERNEL_N
#define CONV_SHUFFLE_KERNEL_K GEMM_SHUFFLE_KERNEL_K
#define FC_SHUFFLE_KERNEL_M GEMM_SHUFFLE_KERNEL_M
#define FC_SHUFFLE_KERNEL_N GEMM_SHUFFLE_KERNEL_N
#define FC_SHUFFLE_KERNEL_K GEMM_SHUFFLE_KERNEL_K
#elif defined(__AVX2__)
#define GEMM_SHUFFLE_KERNEL_M 4
#define GEMM_SHUFFLE_KERNEL_N 8
#define GEMM_SHUFFLE_KERNEL_K 8
#define CONV_SHUFFLE_KERNEL_M GEMM_SHUFFLE_KERNEL_M
#define CONV_SHUFFLE_KERNEL_N GEMM_SHUFFLE_KERNEL_N
#define CONV_SHUFFLE_KERNEL_K GEMM_SHUFFLE_KERNEL_N
#define FC_SHUFFLE_KERNEL_M 4
#define FC_SHUFFLE_KERNEL_N 8
#define FC_SHUFFLE_KERNEL_K 8
#else
#define GEMM_SHUFFLE_KERNEL_M 2
#define GEMM_SHUFFLE_KERNEL_N 2
#define GEMM_SHUFFLE_KERNEL_K 16
#define CONV_SHUFFLE_KERNEL_M GEMM_SHUFFLE_KERNEL_M
#define CONV_SHUFFLE_KERNEL_N GEMM_SHUFFLE_KERNEL_N
#define CONV_SHUFFLE_KERNEL_K GEMM_SHUFFLE_KERNEL_K
#define FC_SHUFFLE_KERNEL_M GEMM_SHUFFLE_KERNEL_M
#define FC_SHUFFLE_KERNEL_N GEMM_SHUFFLE_KERNEL_N
#define FC_SHUFFLE_KERNEL_K GEMM_SHUFFLE_KERNEL_K
#endif


#endif
