/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_intel_analytics_bigdl_mkl_MklDnn */

#ifndef _Included_com_intel_analytics_bigdl_mkl_MklDnn
#define _Included_com_intel_analytics_bigdl_mkl_MklDnn
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_intel_analytics_bigdl_mkl_MklDnn
 * Method:    EngineCreate
 * Signature: (II)J
 */
JNIEXPORT jlong JNICALL Java_com_intel_analytics_bigdl_mkl_MklDnn_EngineCreate
  (JNIEnv *, jclass, jint , jint);

/*
 * Class:     com_intel_analytics_bigdl_mkl_MklDnn
 * Method:    EngineDestroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_intel_analytics_bigdl_mkl_MklDnn_EngineDestroy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_intel_analytics_bigdl_mkl_MklDnn
 * Method:    StreamCreate
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_com_intel_analytics_bigdl_mkl_MklDnn_StreamCreate
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_intel_analytics_bigdl_mkl_MklDnn
 * Method:    StreamSubmit
 * Signature: (JI[J)J
 */
JNIEXPORT jlong JNICALL Java_com_intel_analytics_bigdl_mkl_MklDnn_StreamSubmit
  (JNIEnv *, jclass, jlong, jint, jlongArray, int);

/*
 * Class:     com_intel_analytics_bigdl_mkl_MklDnn
 * Method:    StreamWait
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_com_intel_analytics_bigdl_mkl_MklDnn_StreamWait
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_intel_analytics_bigdl_mkl_MklDnn
 * Method:    StreamDestroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_intel_analytics_bigdl_mkl_MklDnn_StreamDestroy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_intel_analytics_bigdl_mkl_MklDnn
 * Method:    MemoryDescInit
 * Signature: (I[III)J
 */
JNIEXPORT jlong JNICALL Java_com_intel_analytics_bigdl_mkl_MklDnn_MemoryDescInit
  (JNIEnv *, jclass, jint, jintArray, jint, jint);

/*
 * Class:     com_intel_analytics_bigdl_mkl_MklDnn
 * Method:    MemoryPrimitiveDescCreate
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_com_intel_analytics_bigdl_mkl_MklDnn_MemoryPrimitiveDescCreate
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_intel_analytics_bigdl_mkl_MklDnn
 * Method:    MemoryGetDataHandle
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_intel_analytics_bigdl_mkl_MklDnn_MemoryGetDataHandle
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_intel_analytics_bigdl_mkl_MklDnn
 * Method:    MemorySetDataHandle
 * Signature: (JJ)V
 */
JNIEXPORT long JNICALL Java_com_intel_analytics_bigdl_mkl_MklDnn_MemorySetDataHandle
  (JNIEnv *, jclass, jlong, jfloatArray);

JNIEXPORT void JNICALL Java_com_intel_analytics_bigdl_mkl_MklDnn_MemoryReleaseDataHandle
  (JNIEnv *, jclass, jfloatArray, jlong);

/*
 * Class:     com_intel_analytics_bigdl_mkl_MklDnn
 * Method:    PrimitiveCreate
 * Signature: (J[J[J)J
 */
JNIEXPORT jlong JNICALL Java_com_intel_analytics_bigdl_mkl_MklDnn_PrimitiveCreate
  (JNIEnv *, jclass, jlong, jlongArray, jlongArray);

/*
 * Class:     com_intel_analytics_bigdl_mkl_MklDnn
 * Method:    PrimitiveDescCreate
 * Signature: (JIJ)J
 */
JNIEXPORT jlong JNICALL Java_com_intel_analytics_bigdl_mkl_MklDnn_PrimitiveDescCreate
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     com_intel_analytics_bigdl_mkl_MklDnn
 * Method:    PrimitiveDescDestroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_intel_analytics_bigdl_mkl_MklDnn_PrimitiveDescDestroy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_intel_analytics_bigdl_mkl_MklDnn
 * Method:    PrimitiveDestroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_intel_analytics_bigdl_mkl_MklDnn_PrimitiveDestroy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_intel_analytics_bigdl_mkl_MklDnn
 * Method:    PrimitiveCreateForSubmit
 * Signature: (JIJ)J
 */
JNIEXPORT jlong JNICALL Java_com_intel_analytics_bigdl_mkl_MklDnn_PrimitiveCreateForSubmit(
  JNIEnv *, jclass, jlong, jlongArray, int, jlongArray, int);

/*
 * Class:     com_intel_analytics_bigdl_mkl_MklDnn
 * Method:    EltwiseForwardDescInit
 * Signature: (IIJFF)J
 */
JNIEXPORT jlong JNICALL Java_com_intel_analytics_bigdl_mkl_MklDnn_EltwiseForwardDescInit
  (JNIEnv *, jclass, jint, jint, jlong, jfloat, jfloat);

/*
 * Class:     com_intel_analytics_bigdl_mkl_MklDnn
 * Method:    EltwiseBackwardDescInit
 * Signature: (IJJFF)J
 */
JNIEXPORT jlong JNICALL Java_com_intel_analytics_bigdl_mkl_MklDnn_EltwiseBackwardDescInit
  (JNIEnv *, jclass, jint, jlong, jlong, jfloat, jfloat);

#ifdef __cplusplus
}
#endif
#endif
