/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_intel_analytics_bigdl_mkl_Memory */

#ifndef _Included_com_intel_analytics_bigdl_mkl_Memory
#define _Included_com_intel_analytics_bigdl_mkl_Memory
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_intel_analytics_bigdl_mkl_Memory
 * Method:    SetDataHandle
 * Signature: (JJI)J
 */
JNIEXPORT jlong JNICALL Java_com_intel_analytics_bigdl_mkl_Memory_SetDataHandle
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     com_intel_analytics_bigdl_mkl_Memory
 * Method:    Zero
 * Signature: (JII)J
 */
JNIEXPORT jlong JNICALL Java_com_intel_analytics_bigdl_mkl_Memory_Zero
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     com_intel_analytics_bigdl_mkl_Memory
 * Method:    CopyPtr2Ptr
 * Signature: (JIJIII)J
 */
JNIEXPORT jlong JNICALL Java_com_intel_analytics_bigdl_mkl_Memory_CopyPtr2Ptr
  (JNIEnv *, jclass, jlong, jint, jlong, jint, jint, jint);

/*
 * Class:     com_intel_analytics_bigdl_mkl_Memory
 * Method:    CopyArray2Ptr
 * Signature: ([FIJIII)J
 */
JNIEXPORT jlong JNICALL Java_com_intel_analytics_bigdl_mkl_Memory_CopyArray2Ptr
  (JNIEnv *, jclass, jfloatArray, jint, jlong, jint, jint, jint);

/*
 * Class:     com_intel_analytics_bigdl_mkl_Memory
 * Method:    CopyPtr2Array
 * Signature: (JI[FIII)J
 */
JNIEXPORT jlong JNICALL Java_com_intel_analytics_bigdl_mkl_Memory_CopyPtr2Array
  (JNIEnv *, jclass, jlong, jint, jfloatArray, jint, jint, jint);

/*
 * Class:     com_intel_analytics_bigdl_mkl_Memory
 * Method:    AlignedMalloc
 * Signature: (II)J
 */
JNIEXPORT jlong JNICALL Java_com_intel_analytics_bigdl_mkl_Memory_AlignedMalloc
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_intel_analytics_bigdl_mkl_Memory
 * Method:    AlignedFree
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_intel_analytics_bigdl_mkl_Memory_AlignedFree
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
