package com.intel.analytics.bigdl.dnnl;

public class Query {
    public static final int Undef = 0;
    public static final int Engine = 1;
    public static final int PrimitiveKind = 2;
    public static final int NumOfInputsS32 = 3;
    public static final int NumOfOutputsS32 = 4;
    public static final int TimeEstimateF64 = 5;
    public static final int MemoryConsumptionS64 = 6;
    public static final int ScratchpadEngine = 7;
    public static final int ImplInfoStr = 8;
    public static final int ReorderSrcEngine = 9;
    public static final int ReorderDstEngine = 10;
    public static final int PropKind = 11;
    public static final int SomeD = 64;
    public static final int OpD = 65;
    public static final int ConvolutionD = 66;
    public static final int DeconvolutionD = 67;
    public static final int ShuffleD = 68;
    public static final int EltwiseD = 69;
    public static final int SoftmaxD = 70;
    public static final int PoolingD = 71;
    public static final int LrnD = 72;
    public static final int BatchNormalizationD = 73;
    public static final int LayerNormalizationD = 74;
    public static final int InnerProductD = 75;
    public static final int RnnD = 76;
    public static final int GemmD = 77;
    public static final int BinaryD = 78;
    public static final int SomeMd = 128;
    public static final int SrcMd = 129;
    public static final int DiffSrcMd = 130;
    public static final int WeightsMd = 131;
    public static final int DiffWeightsMd = 132;
    public static final int DstMd = 133;
    public static final int DiffDstMd = 134;
    public static final int WorkspaceMd = 135;
    public static final int ScratchpadMd = 136;
}
