/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_intel_analytics_bigdl_ppml_tdx_Attestation */

#ifndef _Included_com_intel_analytics_bigdl_ppml_tdx_Attestation
#define _Included_com_intel_analytics_bigdl_ppml_tdx_Attestation
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_intel_analytics_bigdl_ppml_tdx_Attestation
 * Method:    tdxGenerateQuote
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_intel_analytics_bigdl_ppml_tdx_Attestation_tdxGenerateQuote
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
