/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_intel_analytics_bigdl_mkl_Stream */

#ifndef _Included_com_intel_analytics_bigdl_mkl_Stream
#define _Included_com_intel_analytics_bigdl_mkl_Stream
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_intel_analytics_bigdl_mkl_Stream
 * Method:    Create
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_com_intel_analytics_bigdl_mkl_Stream_Create
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_intel_analytics_bigdl_mkl_Stream
 * Method:    Submit
 * Signature: (JI[J)V
 */
JNIEXPORT void JNICALL Java_com_intel_analytics_bigdl_mkl_Stream_Submit
  (JNIEnv *, jclass, jlong, jint, jlongArray);

/*
 * Class:     com_intel_analytics_bigdl_mkl_Stream
 * Method:    Wait
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_com_intel_analytics_bigdl_mkl_Stream_Wait
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_intel_analytics_bigdl_mkl_Stream
 * Method:    Rerun
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_intel_analytics_bigdl_mkl_Stream_Rerun
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_intel_analytics_bigdl_mkl_Stream
 * Method:    Destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_intel_analytics_bigdl_mkl_Stream_Destroy
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
