/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_intel_analytics_bigdl_ppml_attestation_Attestation */

#ifndef _Included_com_intel_analytics_bigdl_ppml_attestation_Attestation
#define _Included_com_intel_analytics_bigdl_ppml_attestation_Attestation
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_intel_analytics_bigdl_ppml_attestation_Attestation
 * Method:    sdkVerifyQuote
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_com_intel_analytics_bigdl_ppml_attestation_Attestation_sdkVerifyQuote
  (JNIEnv *, jclass, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
