/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_intel_analytics_bigdl_fixpoint_FixPoint */

#ifndef _Included_com_intel_analytics_bigdl_fixpoint_FixPoint
#define _Included_com_intel_analytics_bigdl_fixpoint_FixPoint
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_intel_analytics_bigdl_fixpoint_FixPoint
 * Method:    printHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_intel_analytics_bigdl_fixpoint_FixPoint_printHello
  (JNIEnv *, jclass);

/*
 * Class:     com_intel_analytics_bigdl_fixpoint_FixPoint
 * Method:    FixConvOpCreate
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_com_intel_analytics_bigdl_fixpoint_FixPoint_FixConvOpCreate
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_intel_analytics_bigdl_fixpoint_FixPoint
 * Method:    FixConvOpSetupConvParameter
 * Signature: (JJJJJJJJJJJJ[FJZ[FJZ)V
 */
JNIEXPORT void JNICALL Java_com_intel_analytics_bigdl_fixpoint_FixPoint_FixConvOpSetupConvParameter
  (JNIEnv *, jclass, jlong, jlong, jlong, jlong, jlong, jlong, jlong, jlong, jlong, jlong, jlong, jlong, jfloatArray, jlong, jboolean, jfloatArray, jlong, jboolean);

/*
 * Class:     com_intel_analytics_bigdl_fixpoint_FixPoint
 * Method:    FixConvOpQuantizeKernel
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_com_intel_analytics_bigdl_fixpoint_FixPoint_FixConvOpQuantizeKernel
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     com_intel_analytics_bigdl_fixpoint_FixPoint
 * Method:    FixConvOpQuantizeData
 * Signature: (JJJJJ[FJF)V
 */
JNIEXPORT void JNICALL Java_com_intel_analytics_bigdl_fixpoint_FixPoint_FixConvOpQuantizeData
  (JNIEnv *, jclass, jlong, jlong, jlong, jlong, jlong, jfloatArray, jlong, jfloat);

/*
 * Class:     com_intel_analytics_bigdl_fixpoint_FixPoint
 * Method:    FixConvOpSetupTargetBuffer
 * Signature: (J[FJ)V
 */
JNIEXPORT void JNICALL Java_com_intel_analytics_bigdl_fixpoint_FixPoint_FixConvOpSetupTargetBuffer
  (JNIEnv *, jclass, jlong, jfloatArray, jlong);

/*
 * Class:     com_intel_analytics_bigdl_fixpoint_FixPoint
 * Method:    FixConvOpExecute
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_com_intel_analytics_bigdl_fixpoint_FixPoint_FixConvOpExecute
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     com_intel_analytics_bigdl_fixpoint_FixPoint
 * Method:    FixConvOpFree
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_intel_analytics_bigdl_fixpoint_FixPoint_FixConvOpFree
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
