# vim:noet
include ../../Makefile.common

MKLDNN_INC_DIR=../native/include
MKLDNN_LIB_DIR=../native/build/src/

CFLAGS = -I ${JAVA_HOME}/include/linux
SUFFIX = so

all:
ifeq ($(PLATFORM), LINUX)
include ../Makefile.common
endif
