/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_intel_analytics_bigdl_ckks_CKKS */

#ifndef _Included_com_intel_analytics_bigdl_ckks_CKKS
#define _Included_com_intel_analytics_bigdl_ckks_CKKS
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_intel_analytics_bigdl_ckks_CKKS
 * Method:    createSecrets
 * Signature: ()[[B
 */
JNIEXPORT jobjectArray JNICALL Java_com_intel_analytics_bigdl_ckks_CKKS_createSecrets
  (JNIEnv *, jobject);

/*
 * Class:     com_intel_analytics_bigdl_ckks_CKKS
 * Method:    createCkksEncryptor
 * Signature: ([[B)J
 */
JNIEXPORT jlong JNICALL Java_com_intel_analytics_bigdl_ckks_CKKS_createCkksEncryptor
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     com_intel_analytics_bigdl_ckks_CKKS
 * Method:    ckksEncrypt
 * Signature: (J[F)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_intel_analytics_bigdl_ckks_CKKS_ckksEncrypt
  (JNIEnv *, jobject, jlong, jfloatArray);

/*
 * Class:     com_intel_analytics_bigdl_ckks_CKKS
 * Method:    ckksDecrypt
 * Signature: (J[B)[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_intel_analytics_bigdl_ckks_CKKS_ckksDecrypt
  (JNIEnv *, jobject, jlong, jbyteArray);

/*
 * Class:     com_intel_analytics_bigdl_ckks_CKKS
 * Method:    createCkksCommonInstance
 * Signature: ([[B)J
 */
JNIEXPORT jlong JNICALL Java_com_intel_analytics_bigdl_ckks_CKKS_createCkksCommonInstance
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     com_intel_analytics_bigdl_ckks_CKKS
 * Method:    train
 * Signature: (J[B[B)[[B
 */
JNIEXPORT jobjectArray JNICALL Java_com_intel_analytics_bigdl_ckks_CKKS_train
  (JNIEnv *, jobject, jlong, jbyteArray, jbyteArray);

/*
 * Class:     com_intel_analytics_bigdl_ckks_CKKS
 * Method:    backward
 * Signature: (J[B[B)[[B
 */
JNIEXPORT jobjectArray JNICALL Java_com_intel_analytics_bigdl_ckks_CKKS_backward
  (JNIEnv *, jobject, jlong, jbyteArray, jbyteArray);

/*
 * Class:     com_intel_analytics_bigdl_ckks_CKKS
 * Method:    sigmoidForward
 * Signature: (J[B)[[B
 */
JNIEXPORT jobjectArray JNICALL Java_com_intel_analytics_bigdl_ckks_CKKS_sigmoidForward
  (JNIEnv *, jobject, jlong, jbyteArray);

/*
 * Class:     com_intel_analytics_bigdl_ckks_CKKS
 * Method:    cadd
 * Signature: (J[B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_intel_analytics_bigdl_ckks_CKKS_cadd
  (JNIEnv *, jobject, jlong, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
